# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FairManager' do
    pod 'HanekeSwift', '~> 0.10.1'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Alamofire', '~> 3.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'UIColor_Hex_Swift', '~> 2.1'
end

